name: Run All Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser (chromium, firefox, webkit)'
        required: false
        default: 'chromium'

jobs:
  run-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install --registry=https://registry.npmjs.org/

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run all tests
        run: |
          BROWSER="${{ github.event.inputs.browser }}"
          echo "Spouštím všechny testy s prohlížečem/projektem: $BROWSER"
          npx playwright test --project="$BROWSER"
