name: run-specific-playwright-test

on:
  workflow_dispatch:
    inputs:
      testFile:
        description: 'Path to test file (např. tests/specs/rubrika.spec.ts)'
        required: true
      browser:
        description: 'Browser (chromium, firefox, webkit)'
        required: false

jobs:
  run-single:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install --registry=https://registry.npmjs.org/

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run selected test (default browser: chromium)
        run: |
          BROWSER=${{ github.event.inputs.browser }}
          if [ -z "$BROWSER" ]; then
            BROWSER=chromium
          fi
          npx playwright test ${{ github.event.inputs.testFile }} --project=$BROWSER
